@REM del "%OSGEO4W_STARTMENU%\QGIS Desktop 3.99.0 (Nightly).lnk"
@REM del "%OSGEO4W_STARTMENU%\Qt Designer with QGIS 3.99.0 custom widgets (Nightly).lnk"
@REM del "%OSGEO4W_DESKTOP%\QGIS Desktop 3.99.0 (Nightly).lnk"
@REM del "%OSGEO4W_DESKTOP%\Qt Designer with QGIS 3.99.0 custom widgets (Nightly).lnk"
@REM rmdir "%OSGEO4W_STARTMENU%"
@REM rmdir "%OSGEO4W_DESKTOP%"
@REM del "%OSGEO4W_ROOT%\bin\qgis-dev.bat"
@REM del "%OSGEO4W_ROOT%\bin\qgis-dev-bin.vars"
@REM del "%OSGEO4W_ROOT%\bin\qgis-dev-bin.env"
@REM del "%OSGEO4W_ROOT%\bin\qgis-dev-designer.bat"
@REM del "%OSGEO4W_ROOT%\apps\qgis-dev\python\qgis\qgisconfig.py"
@REM del "%OSGEO4W_ROOT%\apps\qgis-dev\bin\qgis.reg"
@REM del /s /q "%OSGEO4W_ROOT%\apps\qgis-dev\python\*.pyc"
